# Generated by Django 4.1.4 on 2022-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.IntegerField()),
                ('csv_file', models.FileField(upload_to='MainApp/uploads/')),
            ],
        ),
    ]
