# Generated by Django 4.1.4 on 2022-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='timeframe',
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='csv_file',
            field=models.FileField(upload_to=''),
        ),
    ]
